
const Constants = {
    setShowLoading: "[LOADING] Set Show",
    setHiddenLoading: "[LOADING] Set Hidden",

    listModules_onChange: "[ON CHANGE] List Modules",
    paginationModules_onChange: "[ON CHANGE] Pagination Modules",

    tipoRol_setInit: "[SET INIT] Tipo Rol",
    tipoRol_onChange: "[ON CHANGE] Tipo Rol",
    tipoRol_onCreate: "[ON CREATE] Tipo Rol",
    tipoRol_onShow: "[ON SHOW] Tipo Rol",
    tipoRol_onLimpiar: "[ON LIMPIAR] Tipo Rol",

    tipoPermiso_setInit: "[SET INIT] Tipo Permiso",
    tipoPermiso_onChange: "[ON CHANGE] Tipo Permiso",
    tipoPermiso_onShow: "[ON SHOW] Tipo Permiso",
    tipoPermiso_onCreate: "[ON CREATE] Tipo Permiso",
    tipoPermiso_onLimpiar: "[ON LIMPIAR] Tipo Permiso",

    rol_setInit: "[SET INIT] Rol",
    rol_onChange: "[ON CHANGE] Rol",
    rol_onCreate: "[ON CREATE] Rol",
    rol_onShow: "[ON SHOW] Rol",
    rol_onLimpiar: "[ON LIMPIAR] Rol",

    permiso_setInit: "[SET INIT] Permiso",
    permiso_onChange: "[ON CHANGE] Permiso",
    permiso_onCreate: "[ON CREATE] Permiso",
    permiso_onShow: "[ON SHOW] Permiso",
    permiso_onLimpiar: "[ON LIMPIAR] Permiso",

    usuario_setInit: "[SET INIT] Usuario",
    usuario_onChange: "[ON CHANGE] Usuario",
    usuario_onCreate: "[ON CREATE] Usuario",
    usuario_onShow: "[ON SHOW] Usuario",
    usuario_onLimpiar: "[ON LIMPIAR] Usuario",

    nivelAcademico_setInit: "[SET INIT] Nivel Academico",
    nivelAcademico_onChange: "[ON CHANGE] Nivel Academico",
    nivelAcademico_onCreate: "[ON CREATE] Nivel Academico",
    nivelAcademico_onShow: "[ON SHOW] Nivel Academico",
    nivelAcademico_onLimpiar: "[ON LIMPIAR] Nivel Academico",

    modalidad_setInit: "[SET INIT] Modalidad",
    modalidad_onChange: "[ON CHANGE] Modalidad",
    modalidad_onCreate: "[ON CREATE] Modalidad",
    modalidad_onShow: "[ON SHOW] Modalidad",
    modalidad_onLimpiar: "[ON LIMPIAR] Modalidad",

    periodo_setInit: "[SET INIT] Periodo",
    periodo_onCreate: "[ON CREATE] Periodo",
    periodo_onShow: "[ON SHOW] Periodo",
    periodo_onChange: "[ON CHANGE] Periodo",
    periodo_onLimpiar: "[ON LIMPIAR] Periodo",
    
    tipoMateria_setInit: "[SET INIT] Tipo Materia",
    tipoMateria_onChange: "[ON CHANGE] Tipo Materia",
    tipoMateria_onCreate: "[ON CREATE] Tipo Materia",
    tipoMateria_onShow: "[ON SHOW] Tipo Materia",
    tipoMateria_onLimpiar: "[ON LIMPIAR] Tipo Materia",

    materia_setInit: "[SET INIT] Materia",
    materia_onChange: "[ON CHANGE] Materia",
    materia_onCreate: "[ON CREATE] Materia",
    materia_onShow: "[ON SHOW] Materia",
    materia_onLimpiar: "[ON LIMPIAR] Materia",

    ofertaAcademica_setInit: "[SET INIT] Oferta Academica",
    ofertaAcademica_onChange: "[ON CHANGE] Oferta Academica",
    ofertaAcademica_onCreate: "[ON CREATE] Oferta Academica",
    ofertaAcademica_onShow: "[ON SHOW] Oferta Academica",
    ofertaAcademica_onLimpiar: "[ON LIMPIAR] Oferta Academica",

    unidadNegocio_setInit: "[SET INIT] Unidad Negocio",
    unidadNegocio_onCreate: "[ON CREATE] Unidad Negocio",
    unidadNegocio_onShow: "[ON SHOW] Unidad Negocio",
    unidadNegocio_onChange: "[ON CHANGE] Unidad Negocio",
    unidadNegocio_onLimpiar: "[ON LIMPIAR] Unidad Negocio",

    tipociudad_setInit: "[SET INIT] Tipo Ciudad",
    tipociudad_onChange: "[ON CHANGE] Tipo Ciudad",
    tipociudad_onCreate: "[ON CREATE] Tipo Ciudad",
    tipociudad_onShow: "[ON SHOW] Tipo Ciudad",
    tipociudad_onLimpiar: "[ON LIMPIAR] Tipo Ciudad",

    ciudad_setInit: "[SET INIT] Ciudad",
    ciudad_onChange: "[ON CHANGE] Ciudad",
    ciudad_onCreate: "[ON CREATE] Ciudad",
    ciudad_onShow: "[ON SHOW] Ciudad",
    ciudad_onLimpiar: "[ON LIMPIAR] Ciudad",

    referenciaContacto_setInit: "[SET INIT] Referencia Contacto",
    referenciaContacto_onChange: "[ON CHANGE] Referencia Contacto",
    referenciaContacto_onCreate: "[ON CREATE] Referencia Contacto",
    referenciaContacto_onShow: "[ON SHOW] Referencia Contacto",
    referenciaContacto_onLimpiar: "[ON LIMPIAR] Referencia Contacto",

    unidadadministrativa_setInit: "[SET INIT] Unidad Administtrativa",
    unidadadministrativa_onChange: "[ON CHANGE] Unidad Administtrativa",
    unidadadministrativa_onCreate: "[ON CREATE] Unidad Administtrativa",
    unidadadministrativa_onShow: "[ON SHOW] Unidad Administtrativa",
    unidadadministrativa_onLimpiar: "[ON LIMPIAR] Unidad Administtrativa",

    unidadacademica_setInit: "[SET INIT] Unidad Academica",
    unidadacademica_onChange: "[ON CHANGE] Unidad Academica",
    unidadacademica_onCreate: "[ON CREATE] Unidad Academica",
    unidadacademica_onShow: "[ON SHOW] Unidad Academica",
    unidadacademica_onLimpiar: "[ON LIMPIAR] Unidad Academica",

    programa_setInit: "[SET INIT] Programa",
    programa_onChange: "[ON CHANGE] Programa",
    programa_onCreate: "[ON CREATE] Programa",
    programa_onShow: "[ON SHOW] Programa",
    programa_onLimpiar: "[ON LIMPIAR] Programa",

    pensum_setInit: "[SET INIT] Pensum",
    pensum_onChange: "[ON CHANGE] Pensum",
    pensum_onCreate: "[ON CREATE] Pensum",
    pensum_onShow: "[ON SHOW] Pensum",
    pensum_onLimpiar: "[ON LIMPIAR] Pensum",

    responsable_setInit: "[SET INIT] Responsable",
    responsable_onChange: "[ON CHANGE] Responsable",
    responsable_onCreate: "[ON CREATE] Responsable",
    responsable_onShow: "[ON SHOW] Responsable",
    responsable_onLimpiar: "[ON LIMPIAR] Responsable",
    responsable_onAddRefContact: "[ON ADD REFERENCIA CONTACTO] Responsable",
    responsable_onDeleteRowRefContact: "[ON DELETE ROW REFERENCIA CONTACTO] Responsable",
    responsable_onAddUndAcademica: "[ON ADD UNIDAD ACADEMICA] Responsable",
    responsable_onDeleteRowUndAcademica: "[ON DELETE ROW UNIDAD ACADEMICA] Responsable",

    turno_setInit: "[SET INIT] Turno",
    turno_onChange: "[ON CHANGE] Turno",
    turno_onCreate: "[ON CREATE] Turno",
    turno_onShow: "[ON SHOW] Turno",
    turno_onLimpiar: "[ON LIMPIAR] Turno",
    turno_onAddRefContact: "[ON ADD REFERENCIA CONTACTO] Turno",
    turno_onDeleteRowRefContact: "[ON DELETE ROW REFERENCIA CONTACTO] Turno",
    turno_onAddUndAcademica: "[ON ADD UNIDAD ACADEMICA] Turno",
    turno_onDeleteRowUndAcademica: "[ON DELETE ROW UNIDAD ACADEMICA] Turno",

    divisionacademica_setInit: "[SET INIT] Division Academica",
    divisionacademica_onChange: "[ON CHANGE] Division Academica",
    divisionacademica_onCreate: "[ON CREATE] Division Academica",
    divisionacademica_onShow: "[ON SHOW] Division Academica",
    divisionacademica_onLimpiar: "[ON LIMPIAR] Division Academica",
    divisionacademica_onAddRefContact: "[ON ADD REFERENCIA CONTACTO] Division Academica",
    divisionacademica_onDeleteRowRefContact: "[ON DELETE ROW REFERENCIA CONTACTO] Division Academica",
    divisionacademica_onAddUndAcademica: "[ON ADD UNIDAD ACADEMICA] Division Academica",
    divisionacademica_onDeleteRowUndAcademica: "[ON DELETE ROW UNIDAD ACADEMICA] Division Academica",

    institucion_setInit: "[SET INIT] Institucion",
    institucion_onChange: "[ON CHANGE] Institucion",
    institucion_onCreate: "[ON CREATE] Institucion",
    institucion_onShow: "[ON SHOW] Institucion",
    institucion_onLimpiar: "[ON LIMPIAR] Institucion",
    institucion_onAddRefContact: "[ON ADD REFERENCIA CONTACTO] Institucion",
    institucion_onDeleteRowRefContact: "[ON DELETE ROW REFERENCIA CONTACTO] Institucion",
    institucion_onAddUndAcademica: "[ON ADD UNIDAD ACADEMICA] Institucion",
    institucion_onDeleteRowUndAcademica: "[ON DELETE ROW UNIDAD ACADEMICA] Institucion",

    gestionperiodo_setInit: "[SET INIT] Gestion Periodo",
    gestionperiodo_onChange: "[ON CHANGE] Gestion Periodo",
    gestionperiodo_onCreate: "[ON CREATE] Gestion Periodo",
    gestionperiodo_onShow: "[ON SHOW] Gestion Periodo",
    gestionperiodo_onLimpiar: "[ON LIMPIAR] Gestion Periodo",
    gestionperiodo_onAddRefContact: "[ON ADD REFERENCIA CONTACTO] Gestion Periodo",
    gestionperiodo_onDeleteRowRefContact: "[ON DELETE ROW REFERENCIA CONTACTO] Gestion Periodo",
    gestionperiodo_onAddUndAcademica: "[ON ADD UNIDAD ACADEMICA] Gestion Periodo",
    gestionperiodo_onDeleteRowUndAcademica: "[ON DELETE ROW UNIDAD ACADEMICA] Gestion Periodo",


    tipoidentificacion_setInit: "[SET INIT] Tipo Identificacion",
    tipoidentificacion_onChange: "[ON CHANGE] Tipo Identificacion",
    tipoidentificacion_onCreate: "[ON CREATE] Tipo Identificacion",
    tipoidentificacion_onShow: "[ON SHOW] Tipo Identificacion",
    tipoidentificacion_onLimpiar: "[ON LIMPIAR] Tipo Identificacion",
    tipoidentificacion_onAddRefContact: "[ON ADD REFERENCIA CONTACTO] Tipo Identificacion",
    tipoidentificacion_onDeleteRowRefContact: "[ON DELETE ROW REFERENCIA CONTACTO] Tipo Identificacion",
    tipoidentificacion_onAddUndAcademica: "[ON ADD UNIDAD ACADEMICA] Tipo Identificacion",
    tipoidentificacion_onDeleteRowUndAcademica: "[ON DELETE ROW UNIDAD ACADEMICA] Tipo Identificacion",

    cargo_setInit: "[SET INIT] Cargo",
    cargo_onChange: "[ON CHANGE] Cargo",
    cargo_onCreate: "[ON CREATE] Cargo",
    cargo_onShow: "[ON SHOW] Cargo",
    cargo_onLimpiar: "[ON LIMPIAR] Cargo",
    cargo_onAddRefContact: "[ON ADD REFERENCIA CONTACTO] Cargo",
    cargo_onDeleteRowRefContact: "[ON DELETE ROW REFERENCIA CONTACTO] Cargo",
    cargo_onAddUndAcademica: "[ON ADD UNIDAD ACADEMICA] Cargo",
    cargo_onDeleteRowUndAcademica: "[ON DELETE ROW UNIDAD ACADEMICA] Cargo",
};

export default Constants;
