
const Constants = {

    login_onChange: "[ON CHANGE] LOGIN",
    login_onLimpiar: "[ON LIMPIAR] LOGIN",

    register_onChange: "[ON CHANGE] REGISTER",
    register_onLimpiar: "[ON LIMPIAR] REGISTER",

    profile_onChange: "[ON CHANGE] Profile",
    profile_onCreate: "[ON CREATE] Profile",
    profile_onShow: "[ON SHOW] Profile",
    profile_onLimpiar: "[ON LIMPIAR] Profile",

    setShowSesion: "[SESION] Set Show",
    setHiddenSesion: "[SESION] Set Hidden",

    setShowLoading: "[LOADING] Set Show",
    setHiddenLoading: "[LOADING] Set Hidden",

    listModules_onChange: "[ON CHANGE] List Modules",
    paginationModules_onChange: "[ON CHANGE] Pagination Modules",

    bitacora_onShow: "[ON SHOW] Bitacora",
    bitacora_onLimpiar: "[ON LIMPIAR] Bitacora",

    tipoRol_setInit: "[SET INIT] Tipo Rol",
    tipoRol_onChange: "[ON CHANGE] Tipo Rol",
    tipoRol_onCreate: "[ON CREATE] Tipo Rol",
    tipoRol_onShow: "[ON SHOW] Tipo Rol",
    tipoRol_onLimpiar: "[ON LIMPIAR] Tipo Rol",

    tipoPermiso_setInit: "[SET INIT] Tipo Permiso",
    tipoPermiso_onChange: "[ON CHANGE] Tipo Permiso",
    tipoPermiso_onShow: "[ON SHOW] Tipo Permiso",
    tipoPermiso_onCreate: "[ON CREATE] Tipo Permiso",
    tipoPermiso_onLimpiar: "[ON LIMPIAR] Tipo Permiso",

    rol_setInit: "[SET INIT] Rol",
    rol_onChange: "[ON CHANGE] Rol",
    rol_onCreate: "[ON CREATE] Rol",
    rol_onShow: "[ON SHOW] Rol",
    rol_onLimpiar: "[ON LIMPIAR] Rol",

    permiso_setInit: "[SET INIT] Permiso",
    permiso_onChange: "[ON CHANGE] Permiso",
    permiso_onCreate: "[ON CREATE] Permiso",
    permiso_onShow: "[ON SHOW] Permiso",
    permiso_onLimpiar: "[ON LIMPIAR] Permiso",

    usuario_setInit: "[SET INIT] Usuario",
    usuario_onChange: "[ON CHANGE] Usuario",
    usuario_onCreate: "[ON CREATE] Usuario",
    usuario_onShow: "[ON SHOW] Usuario",
    usuario_onLimpiar: "[ON LIMPIAR] Usuario",

    asignarrol_setInit: "[SET INIT] Asignar Rol",
    asignarrol_onChange: "[ON CHANGE] Asignar Rol",
    asignarrol_onCreate: "[ON CREATE] Asignar Rol",
    asignarrol_onShow: "[ON SHOW] Asignar Rol",
    asignarrol_onLimpiar: "[ON LIMPIAR] Asignar Rol",


    nivelAcademico_setInit: "[SET INIT] Nivel Academico",
    nivelAcademico_onChange: "[ON CHANGE] Nivel Academico",
    nivelAcademico_onCreate: "[ON CREATE] Nivel Academico",
    nivelAcademico_onShow: "[ON SHOW] Nivel Academico",
    nivelAcademico_onLimpiar: "[ON LIMPIAR] Nivel Academico",

    modalidad_setInit: "[SET INIT] Modalidad",
    modalidad_onChange: "[ON CHANGE] Modalidad",
    modalidad_onCreate: "[ON CREATE] Modalidad",
    modalidad_onShow: "[ON SHOW] Modalidad",
    modalidad_onLimpiar: "[ON LIMPIAR] Modalidad",

    periodo_setInit: "[SET INIT] Periodo",
    periodo_onCreate: "[ON CREATE] Periodo",
    periodo_onShow: "[ON SHOW] Periodo",
    periodo_onChange: "[ON CHANGE] Periodo",
    periodo_onLimpiar: "[ON LIMPIAR] Periodo",
    
    tipoMateria_setInit: "[SET INIT] Tipo Materia",
    tipoMateria_onChange: "[ON CHANGE] Tipo Materia",
    tipoMateria_onCreate: "[ON CREATE] Tipo Materia",
    tipoMateria_onShow: "[ON SHOW] Tipo Materia",
    tipoMateria_onLimpiar: "[ON LIMPIAR] Tipo Materia",

    materia_setInit: "[SET INIT] Materia",
    materia_onChange: "[ON CHANGE] Materia",
    materia_onCreate: "[ON CREATE] Materia",
    materia_onShow: "[ON SHOW] Materia",
    materia_onLimpiar: "[ON LIMPIAR] Materia",

    ofertaAcademica_setInit: "[SET INIT] Oferta Academica",
    ofertaAcademica_onChange: "[ON CHANGE] Oferta Academica",
    ofertaAcademica_onCreate: "[ON CREATE] Oferta Academica",
    ofertaAcademica_onShow: "[ON SHOW] Oferta Academica",
    ofertaAcademica_onLimpiar: "[ON LIMPIAR] Oferta Academica",

    unidadNegocio_setInit: "[SET INIT] Unidad Negocio",
    unidadNegocio_onCreate: "[ON CREATE] Unidad Negocio",
    unidadNegocio_onShow: "[ON SHOW] Unidad Negocio",
    unidadNegocio_onChange: "[ON CHANGE] Unidad Negocio",
    unidadNegocio_onLimpiar: "[ON LIMPIAR] Unidad Negocio",

    tipociudad_setInit: "[SET INIT] Tipo Ciudad",
    tipociudad_onChange: "[ON CHANGE] Tipo Ciudad",
    tipociudad_onCreate: "[ON CREATE] Tipo Ciudad",
    tipociudad_onShow: "[ON SHOW] Tipo Ciudad",
    tipociudad_onLimpiar: "[ON LIMPIAR] Tipo Ciudad",

    ciudad_setInit: "[SET INIT] Ciudad",
    ciudad_onChange: "[ON CHANGE] Ciudad",
    ciudad_onCreate: "[ON CREATE] Ciudad",
    ciudad_onShow: "[ON SHOW] Ciudad",
    ciudad_onLimpiar: "[ON LIMPIAR] Ciudad",

    unidadadministrativa_setInit: "[SET INIT] Unidad Administtrativa",
    unidadadministrativa_onChange: "[ON CHANGE] Unidad Administtrativa",
    unidadadministrativa_onCreate: "[ON CREATE] Unidad Administtrativa",
    unidadadministrativa_onShow: "[ON SHOW] Unidad Administtrativa",
    unidadadministrativa_onLimpiar: "[ON LIMPIAR] Unidad Administtrativa",
    unidadadministrativa_onAddRowTurno: "[ON ADD ROW TURNO] Unidad Administtrativa",
    unidadadministrativa_onDeleteRowTurno: "[ON DELETE ROW TURNO] Unidad Administtrativa",
    unidadadministrativa_onAddRowAula: "[ON ADD ROW AULA] Unidad Administtrativa",
    unidadadministrativa_onDeleteRowAula: "[ON DELETE ROW AULA] Unidad Administtrativa",

    unidadacademica_setInit: "[SET INIT] Unidad Academica",
    unidadacademica_onChange: "[ON CHANGE] Unidad Academica",
    unidadacademica_onCreate: "[ON CREATE] Unidad Academica",
    unidadacademica_onShow: "[ON SHOW] Unidad Academica",
    unidadacademica_onLimpiar: "[ON LIMPIAR] Unidad Academica",

    programa_setInit: "[SET INIT] Programa",
    programa_onChange: "[ON CHANGE] Programa",
    programa_onCreate: "[ON CREATE] Programa",
    programa_onShow: "[ON SHOW] Programa",
    programa_onLimpiar: "[ON LIMPIAR] Programa",
    programa_onAddRowMallaCurricular: "[ON ADD ROW MALLA CURRICULAR] Programa",
    programa_onDeleteRowMallaCurricular: "[ON DELETE ROW MALLA CURRICULAR] Programa",
    programa_onAddRowMateriaDetail: "[ON ADD ROW MATERIA DETAILS] Programa",
    programa_onDeletRowMateriaDetail: "[ON DELETE ROW MATERIA DETAILS] Programa",

    pensum_setInit: "[SET INIT] Pensum",
    pensum_onChange: "[ON CHANGE] Pensum",
    pensum_onCreate: "[ON CREATE] Pensum",
    pensum_onShow: "[ON SHOW] Pensum",
    pensum_onLimpiar: "[ON LIMPIAR] Pensum",
    pensum_onAddRowDivisionAcademica: "[ON ADD ROW DIVISION ACADEMICA] Pensum",
    pensum_onDeleteRowDivisionAcademica: "[ON DELETE ROW DIVISION ACADEMICA] Pensum",
    pensum_onAddRowMateriaDetails: "[ON ADD ROW MATERIA DETAILS] Pensum",
    pensum_onDeleteRowMateriaDetails: "[ON DELETE ROW MATERIA DETAILS] Pensum",

    responsable_setInit: "[SET INIT] Responsable",
    responsable_onChange: "[ON CHANGE] Responsable",
    responsable_onCreate: "[ON CREATE] Responsable",
    responsable_onShow: "[ON SHOW] Responsable",
    responsable_onLimpiar: "[ON LIMPIAR] Responsable",
    responsable_onAddRefContact: "[ON ADD REFERENCIA CONTACTO] Responsable",
    responsable_onDeleteRowRefContact: "[ON DELETE ROW REFERENCIA CONTACTO] Responsable",
    responsable_onAddUndAcademica: "[ON ADD UNIDAD ACADEMICA] Responsable",
    responsable_onDeleteRowUndAcademica: "[ON DELETE ROW UNIDAD ACADEMICA] Responsable",

    turno_setInit: "[SET INIT] Turno",
    turno_onChange: "[ON CHANGE] Turno",
    turno_onCreate: "[ON CREATE] Turno",
    turno_onShow: "[ON SHOW] Turno",
    turno_onLimpiar: "[ON LIMPIAR] Turno",

    aula_setInit: "[SET INIT] Aula",
    aula_onChange: "[ON CHANGE] Aula",
    aula_onCreate: "[ON CREATE] Aula",
    aula_onShow: "[ON SHOW] Aula",
    aula_onLimpiar: "[ON LIMPIAR] Aula",

    divisionacademica_setInit: "[SET INIT] Division Academica",
    divisionacademica_onChange: "[ON CHANGE] Division Academica",
    divisionacademica_onCreate: "[ON CREATE] Division Academica",
    divisionacademica_onShow: "[ON SHOW] Division Academica",
    divisionacademica_onLimpiar: "[ON LIMPIAR] Division Academica",

    institucion_setInit: "[SET INIT] Institucion",
    institucion_onChange: "[ON CHANGE] Institucion",
    institucion_onCreate: "[ON CREATE] Institucion",
    institucion_onShow: "[ON SHOW] Institucion",
    institucion_onLimpiar: "[ON LIMPIAR] Institucion",

    gestionperiodo_setInit: "[SET INIT] Gestion Periodo",
    gestionperiodo_onChange: "[ON CHANGE] Gestion Periodo",
    gestionperiodo_onCreate: "[ON CREATE] Gestion Periodo",
    gestionperiodo_onShow: "[ON SHOW] Gestion Periodo",
    gestionperiodo_onLimpiar: "[ON LIMPIAR] Gestion Periodo",


    tipoidentificacion_setInit: "[SET INIT] Tipo Identificacion",
    tipoidentificacion_onChange: "[ON CHANGE] Tipo Identificacion",
    tipoidentificacion_onCreate: "[ON CREATE] Tipo Identificacion",
    tipoidentificacion_onShow: "[ON SHOW] Tipo Identificacion",
    tipoidentificacion_onLimpiar: "[ON LIMPIAR] Tipo Identificacion",

    categoriadocumento_setInit: "[SET INIT] Categoria Documento",
    categoriadocumento_onChange: "[ON CHANGE] Categoria Documento",
    categoriadocumento_onCreate: "[ON CREATE] Categoria Documento",
    categoriadocumento_onShow: "[ON SHOW] Categoria Documento",
    categoriadocumento_onLimpiar: "[ON LIMPIAR] Categoria Documento",

    cargo_setInit: "[SET INIT] Cargo",
    cargo_onChange: "[ON CHANGE] Cargo",
    cargo_onCreate: "[ON CREATE] Cargo",
    cargo_onShow: "[ON SHOW] Cargo",
    cargo_onLimpiar: "[ON LIMPIAR] Cargo",

    docente_setInit: "[SET INIT] Docente",
    docente_onChange: "[ON CHANGE] Docente",
    docente_onCreate: "[ON CREATE] Docente",
    docente_onShow: "[ON SHOW] Docente",
    docente_onLimpiar: "[ON LIMPIAR] Docente",
    docente_onAddRowNacionalidad: "[ON ADD ROW NACIONALIDAD] Docente",
    docente_onDeleteRowNacionalidad: "[ON DELETE ROW NACIONALIDAD] Docente",
    docente_onAddRowMateria: "[ON ADD ROW MATERIA] Docente",
    docente_onDeleteRowMateria: "[ON DELETE ROW MATERIA] Docente",
    docente_onAddRowCategoriaDocumento: "[ON ADD ROW CATEGORIA DOCUMENTO] Docente",
    docente_onDeleteRowCategoriaDocumento: "[ON DELETE ROW CATEGORIA DOCUMENTO] Docente",
    docente_onAddRowEstudio: "[ON ADD ROW ESTUDIO] Docente",
    docente_onDeleteRowEstudio: "[ON DELETE ROW ESTUDIO] Docente",

    estudiante_setInit: "[SET INIT] Estudiante",
    estudiante_onChange: "[ON CHANGE] Estudiante",
    estudiante_onCreate: "[ON CREATE] Estudiante",
    estudiante_onShow: "[ON SHOW] Estudiante",
    estudiante_onLimpiar: "[ON LIMPIAR] Estudiante",
    estudiante_onAddRowNacionalidad: "[ON ADD ROW NACIONALIDAD] Estudiante",
    estudiante_onDeleteRowNacionalidad: "[ON DELETE ROW NACIONALIDAD] Estudiante",
    estudiante_onAddRowCategoriaDocumento: "[ON ADD ROW CATEGORIA DOCUMENTO] Estudiante",
    estudiante_onDeleteRowCategoriaDocumento: "[ON DELETE ROW CATEGORIA DOCUMENTO] Estudiante",
    estudiante_onAddRowFamiliar: "[ON ADD ROW FAMILIAR] Estudiante",
    estudiante_onDeleteRowFamiliar: "[ON DELETE ROW FAMILIAR] Estudiante",

    administrativo_setInit: "[SET INIT] Administrativo",
    administrativo_onChange: "[ON CHANGE] Administrativo",
    administrativo_onCreate: "[ON CREATE] Administrativo",
    administrativo_onShow: "[ON SHOW] Administrativo",
    administrativo_onLimpiar: "[ON LIMPIAR] Administrativo",
    administrativo_onAddRowNacionalidad: "[ON ADD ROW NACIONALIDAD] Administrativo",
    administrativo_onDeleteRowNacionalidad: "[ON DELETE ROW NACIONALIDAD] Administrativo",
    administrativo_onAddRowCategoriaDocumento: "[ON ADD ROW CATEGORIA DOCUMENTO] Administrativo",
    administrativo_onDeleteRowCategoriaDocumento: "[ON DELETE ROW CATEGORIA DOCUMENTO] Administrativo",
    administrativo_onAddRowEstudio: "[ON ADD ROW ESTUDIO] Administrativo",
    administrativo_onDeleteRowEstudio: "[ON DELETE ROW ESTUDIO] Administrativo",


    curso_setInit: "[SET INIT] Curso",
    curso_onChange: "[ON CHANGE] Curso",
    curso_onCreate: "[ON CREATE] Curso",
    curso_onShow: "[ON SHOW] Curso",
    curso_onLimpiar: "[ON LIMPIAR] Curso",
    curso_onAddRowParametroCalificacion: "[ON ADD ROW PARAMETRO CALIFICACION] Curso",
    curso_onDeleteRowParametroCalificacion: "[ON DELETE ROW PARAMETRO CALIFICACION] Curso",
    curso_onAddRowDocente: "[ON ADD ROW DOCENTE] Curso",
    curso_onDeleteRowDocente: "[ON DELETE ROW DOCENTE] Curso",

    cursohorario_onChange: "[ON CHANGE] Curso Horario",
    cursohorario_onLimpiar: "[ON LIMPIAR] Curso Horario",
    cursohorario_onAddRowHorario: "[ON ADD ROW HORARIO] Curso Horario",
    cursohorario_onDeleteRowHorario: "[ON DELETE ROW HORARIO] Curso Horario",

    motivoaperturacierrecurso_setInit: "[SET INIT] Motivo Apertura Cierre Curso",
    motivoaperturacierrecurso_onChange: "[ON CHANGE] Motivo Apertura Cierre Curso",
    motivoaperturacierrecurso_onCreate: "[ON CREATE] Motivo Apertura Cierre Curso",
    motivoaperturacierrecurso_onShow: "[ON SHOW] Motivo Apertura Cierre Curso",
    motivoaperturacierrecurso_onLimpiar: "[ON LIMPIAR] Motivo Apertura Cierre Curso",

    grupo_setInit: "[SET INIT] Grupo",
    grupo_onChange: "[ON CHANGE] Grupo",
    grupo_onCreate: "[ON CREATE] Grupo",
    grupo_onShow: "[ON SHOW] Grupo",
    grupo_onLimpiar: "[ON LIMPIAR] Grupo",
    grupo_onAddRowPensum: "[ON ADD ROW PENSUM] Grupo",
    grupo_onDeleteRowPensum: "[ON DELETE ROW PENSUM] Grupo",

    tipoactividad_setInit: "[SET INIT] Tipo Actividad",
    tipoactividad_onChange: "[ON CHANGE] Tipo Actividad",
    tipoactividad_onCreate: "[ON CREATE] Tipo Actividad",
    tipoactividad_onShow: "[ON SHOW] Tipo Actividad",
    tipoactividad_onLimpiar: "[ON LIMPIAR] Tipo Actividad",

    tipomediopublicitario_setInit: "[SET INIT] Tipo Medio Publicitario",
    tipomediopublicitario_onChange: "[ON CHANGE] Tipo Medio Publicitario",
    tipomediopublicitario_onCreate: "[ON CREATE] Tipo Medio Publicitario",
    tipomediopublicitario_onShow: "[ON SHOW] Tipo Medio Publicitario",
    tipomediopublicitario_onLimpiar: "[ON LIMPIAR] Tipo Medio Publicitario",

    tipocontacto_setInit: "[SET INIT] Tipo Contacto",
    tipocontacto_onChange: "[ON CHANGE] Tipo Contacto",
    tipocontacto_onCreate: "[ON CREATE] Tipo Contacto",
    tipocontacto_onShow: "[ON SHOW] Tipo Contacto",
    tipocontacto_onLimpiar: "[ON LIMPIAR] Tipo Contacto",

    estadonegocio_setInit: "[SET INIT] Estado Negocio",
    estadonegocio_onChange: "[ON CHANGE] Estado Negocio",
    estadonegocio_onCreate: "[ON CREATE] Estado Negocio",
    estadonegocio_onShow: "[ON SHOW] Estado Negocio",
    estadonegocio_onLimpiar: "[ON LIMPIAR] Estado Negocio",

    tiporesultado_setInit: "[SET INIT] Tipo Resultado",
    tiporesultado_onChange: "[ON CHANGE] Tipo Resultado",
    tiporesultado_onCreate: "[ON CREATE] Tipo Resultado",
    tiporesultado_onShow: "[ON SHOW] Tipo Resultado",
    tiporesultado_onLimpiar: "[ON LIMPIAR] Tipo Resultado",

    asesorresponsable_setInit: "[SET INIT] Asesor Responsable",
    asesorresponsable_onChange: "[ON CHANGE] Asesor Responsable",
    asesorresponsable_onCreate: "[ON CREATE] Asesor Responsable",
    asesorresponsable_onShow: "[ON SHOW] Asesor Responsable",
    asesorresponsable_onLimpiar: "[ON LIMPIAR] Asesor Responsable",

    negocio_setInit: "[SET INIT] Negocio",
    negocio_onChange: "[ON CHANGE] Negocio",
    negocio_onCreate: "[ON CREATE] Negocio",
    negocio_onCreateNegocio: "[ON INIT CREATE] Negocio",
    negocio_onShow: "[ON SHOW] Negocio",
    negocio_onLimpiar: "[ON LIMPIAR] Negocio",

    actividad_setInit: "[SET INIT] Actividad",
    actividad_onChange: "[ON CHANGE] Actividad",
    actividad_onCreate: "[ON CREATE] Actividad",
    actividad_onCreateActividad: "[ON INIT CREATE] Actividad",
    actividad_onShow: "[ON SHOW] Actividad",
    actividad_onLimpiar: "[ON LIMPIAR] Actividad",

    oportunidad_setInit: "[SET INIT] Oportunidad",
    oportunidad_onChange: "[ON CHANGE] Oportunidad",
    oportunidad_onCreate: "[ON CREATE] Oportunidad",
    oportunidad_onShow: "[ON SHOW] Oportunidad",
    oportunidad_onLimpiar: "[ON LIMPIAR] Oportunidad",
    oportundiad_onAddRowTipoContacto: "[ON ADD ROW TIPO CONTACTO] Oportunidad",
    oportundiad_onDeleteRowTipoContacto: "[ON DELETE ROW TIPO CONTACTO] Oportunidad",
    oportundiad_onAddRowTipoMedioPublicitario: "[ON ADD ROW TIPO MEDIO PUBLICITARIO] Oportunidad",
    oportundiad_onDeleteRowTipoMedioPublicitario: "[ON DELETE ROW TIPO MEDIO PUBLICITARIO] Oportunidad",
    oportundiad_onAddRowNegocio: "[ON ADD ROW NEGOCIO] Oportunidad",
    oportundiad_onDeleteRowNegocio: "[ON DELETE ROW NEGOCIO] Oportunidad",


    inscripcionprograma_setInit: "[SET INIT] Inscripción Programa",
    inscripcionprograma_onChange: "[ON CHANGE] Inscripción Programa",
    inscripcionprograma_onCreate: "[ON CREATE] Inscripción Programa",
    inscripcionprograma_onShow: "[ON SHOW] Inscripción Programa",
    inscripcionprograma_onLimpiar: "[ON LIMPIAR] Inscripción Programa",

    inscripcioncurso_setInit: "[SET INIT] Inscripción Curso",
    inscripcioncurso_onChange: "[ON CHANGE] Inscripción Curso",
    inscripcioncurso_onCreate: "[ON CREATE] Inscripción Curso",
    inscripcioncurso_onShow: "[ON SHOW] Inscripción Curso",
    inscripcioncurso_onLimpiar: "[ON LIMPIAR] Inscripción Curso",

    inscripciongrupo_setInit: "[SET INIT] Inscripción Grupo",
    inscripciongrupo_onChange: "[ON CHANGE] Inscripción Grupo",
    inscripciongrupo_onCreate: "[ON CREATE] Inscripción Grupo",
    inscripciongrupo_onShow: "[ON SHOW] Inscripción Grupo",
    inscripciongrupo_onLimpiar: "[ON LIMPIAR] Inscripción Grupo",



    parametrocalificacion_setInit: "[SET INIT] Parametro Calificacion",
    parametrocalificacion_onChange: "[ON CHANGE] Parametro Calificacion",
    parametrocalificacion_onCreate: "[ON CREATE] Parametro Calificacion",
    parametrocalificacion_onShow: "[ON SHOW] Parametro Calificacion",
    parametrocalificacion_onLimpiar: "[ON LIMPIAR] Parametro Calificacion",

    calendarioacademico_setInit: "[SET INIT] Calendario Academico",
    calendarioacademico_onChange: "[ON CHANGE] Calendario Academico",
    calendarioacademico_onCreate: "[ON CREATE] Calendario Academico",
    calendarioacademico_onShow: "[ON SHOW] Calendario Academico",
    calendarioacademico_onLimpiar: "[ON LIMPIAR] Calendario Academico",

    asistenciagrupo_onChange: "[ON CHANGE] Asistencia Grupo",
    asistenciagrupo_onLimpiar: "[ON LIMPIAR] Asistencia Grupo",

    asistenciacurso_onChange: "[ON CHANGE] Asistencia Curso",
    asistenciacurso_onLimpiar: "[ON LIMPIAR] Asistencia Curso",

    notacurso_onChange: "[ON CHANGE] Nota Curso",
    notacurso_onLimpiar: "[ON LIMPIAR] Nota Curso",

    notagrupo_onChange: "[ON CHANGE] Nota Grupo",
    notagrupo_onLimpiar: "[ON LIMPIAR] Nota Grupo",

};

export default Constants;
