
const ColumnModules = {
    columnUnidadNegocio: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnOfertaAcademica: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnNivelAcademico: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnModalidadAcademica: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],
    
    columnPeriodo: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnMateria: [
        {
            id: 'codigo',
            label: 'Código',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'nombrecorto',
            label: 'Nombre Corto',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'nombrelargo',
            label: 'Nombre Largo',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnTipoMateria: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnTipoPermiso: [
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnTipoRol: [
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnRol: [
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'tiporol',
            label: 'Tipo',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnUsuario: [
        {
            id: 'login',
            label: 'Login',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'email',
            label: 'Email',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnUnidadAdministrativa: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'unidadnegocio',
            label: 'Unidad Negocio',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnUnidadAcademica: [
        {
            id: 'codigo',
            label: 'Código',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'unidadadministrativa',
            label: 'Unidad Administrativa',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'unidadnegocio',
            label: 'Unidad Negocio',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnPrograma: [
        {
            id: 'nivelacademico',
            label: 'Nivel',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'modalidadacademica',
            label: 'Modalidad',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'codigo',
            label: 'Código',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'unidadadministrativa',
            label: 'Unidad Administrativa',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'unidadnegocio',
            label: 'Unidad Negocio',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'unidadacademica',
            label: 'Unidad Academica',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],

    columnPensum: [
        {
            id: 'unidadadministrativa',
            label: 'Unidad Administrativa',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'unidadnegocio',
            label: 'Unidad Negocio',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'unidadacademica',
            label: 'Unidad Academica',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'programa',
            label: 'Programa',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'fechaaprobacion',
            label: 'Fecha',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
    ],
};

export default ColumnModules;
