
const ColumnModules = {
    columnUnidadNegocio: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnOfertaAcademica: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnNivelAcademico: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnModalidadAcademica: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],
    
    columnPeriodo: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnMateria: [
        {
            id: 'codigo',
            label: 'Código',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'nombrecorto',
            label: 'Nombre Corto',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'nombrelargo',
            label: 'Nombre Largo',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnTipoMateria: [
        {
            id: 'sigla',
            label: 'Sigla',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnTipoPermiso: [
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnTipoRol: [
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnRol: [
        {
            id: 'descripcion',
            label: 'Descripción',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'tiporol',
            label: 'Tipo',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],

    columnUsuario: [
        {
            id: 'login',
            label: 'Login',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'email',
            label: 'Email',
            numeric: false,
            visible: true,
            width: null,
            state: false,
        },
        {
            id: 'estado',
            label: 'Estado',
            numeric: false,
            visible: true,
            width: null,
            state: true,
        },
        {
            id: 'concurrencia',
            label: 'Concurrencia',
            numeric: true,
            visible: true,
            width: null,
            state: false,
        },
    ],
};

export default ColumnModules;
